### ISSUE TITLE
BUG: Missing Daily folder crashes system when trying to save image

### ISSUE THREAD

**Issue by wiegraebe** [aics-int/microscope_automation#27]
- [x] I have checked that this issue has not already been reported.

- [x] I have confirmed this bug exists on the latest version of microscope_automation.

---

## Description
If path for daily folder does not exists an empty string is used as daily path. This will create an folder in the app directory and crash the app when we try to save images.

## Expected Behavior
As user to manually select daily folder

## Reproduction
Use an invalid path for PathDailyFolder in preferences

```python
   # find path to daily folder. Should reside in settings file.
    # read list with possible paths for daily folder from preferences.yml
    daily_folder = get_valid_path_from_prefs(prefs, "PathDailyFolder")
    daily_path = os.path.normpath(
        os.path.join(daily_folder, folder_name, microscope_name)
    )

    # test if folder exists, if not, create folder
    if not os.path.isdir(daily_path):
        os.makedirs(daily_path)

```

## Environment
*Any additional information about your environment*

**Comment by wiegraebe** [comment]
Related bug: two folder structures are created one based on date, the other based on barcode.

**Comment by fletchapin** [comment]
The barcode vs. date construction is intentional, i.e. the original code preferred using a barcode but if no barcode is given then it will use the date, so I maintained that functionality

**Comment by fletchapin** [comment]
Also, I think the root cause of this is that `get_valid_path_from_prefs` returns an empty string instead of prompting the user that the path was invalid and to select another, so I can look into updating the logic
