### ISSUE TITLE
BUG: Handle if image is not two dimensional

### ISSUE THREAD

**Issue by wiegraebe** [aics-int/microscope_automation#33]
https://github.com/aics-int/microscope_automation/blob/abecb45022636498489af32098b5ebbfee689661/microscope_automation/microscope_automation.py#L2110

Short term solution:
`imsave(image_path, image_data_save.squeeze().T, cmap="gray")`

**Comment by fletchapin** [comment]
Duplicate of #32 so adding this info as a comment there
