### ISSUE TITLE
BUG: Handle missing keys in preferences file for macros

### ISSUE THREAD

**Issue by wiegraebe** [aics-int/microscope_automation#38]
- [x] I have checked that this issue has not already been reported.

- [x] I have confirmed this bug exists on the latest version of microscope_automation.

---

**Note**: Please read [this guide](https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) detailing how to provide the necessary information for us to reproduce your bug.

## Description
Handle missing preferences in microscope_automation.run_macro

## Expected Behavior
If preferences keys are missing or have wrong values, allow user to fix

## Reproduction
Run software with missing keyword 'MacroParams' in preferences file

```python
       macro_name = imaging_settings.get_pref("MacroName")
        param_list = imaging_settings.get_pref("MacroParams")

```

**Comment by fletchapin** [comment]
This seems closely related to #29
