### ISSUE TITLE
BUG: Allow interactive position picking even if segmentation did not return positions

### ISSUE THREAD

**Issue by wiegraebe** [aics-int/microscope_automation#40]
- [x] I have checked that this issue has not already been reported.

- [x] I have confirmed this bug exists on the latest version of microscope_automation.

---

**Note**: Please read [this guide](https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) detailing how to provide the necessary information for us to reproduce your bug.

## Description
If segmentation in microscope_automation.segment_wells returns empty segmentation_info_dict, user does not have option to add positions manually and software crashes when calling
```python
        position_list_for_csv = pos_list_saver.convert_to_stage_coords(
            positions_list=position_list_for_csv
```
## Expected Behavior
Display position picker even if no positions were found and allow user to add positions at
```python
                location_list = well_object.set_interactive_positions(
                    image_data, segmented_position_list, app
                )

```

Even if no positions are picked, software should not crash.

## Reproduction
*A minimal example that exhibits the behavior.*

```python
# Your code here

```

## Environment
*Any additional information about your environment*

**Comment by fletchapin** [comment]
@wiegraebe I'm not 100% clear on how the position picker works. E.g. you say to call the position picker but I'm not quite sure how. It may be easier to chat about this so I can get a clearer picture tomorrow.

**Comment by fletchapin** [comment]
It's impossible to call the position picker when there is an empty `segmentation_info_dict` because the `image_data` comes from that dictionary.

With that said, I will make it so if no positions are picked the software doesn't crash.
