### ISSUE TITLE
BUG: Handle missing positions_output_a file

### ISSUE THREAD

**Issue by wiegraebe** [aics-int/microscope_automation#41]
- [x] I have checked that this issue has not already been reported.

- [x] I have confirmed this bug exists on the latest version of microscope_automation.

---

**Note**: Please read [this guide](https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) detailing how to provide the necessary information for us to reproduce your bug.

## Description
write_zen_tiles_experiment.get_next_pos_name crashes when no file that starts with "positions_output_" exists.

## Expected Behavior
Return 'a' if no file exists.

## Reproduction
Run experiment "SegmentWells" without positions_output file in ZSD folder

The following code can solve the issue:

```python
       if test_mode:
            prefixed = test_file_names
        else:
            prefixed = [
                filename
                for filename in os.listdir(self.path)
                if filename.startswith("positions_output_")
            ]

        if len(prefixed) == 0:
            return 'a'
        # Split extension from name of file
        split = prefixed[len(prefixed) - 1].split(".")
```

## Environment
*Any additional information about your environment*

**Comment by fletchapin** [comment]
I'll add this code and modify the test cases accodingly.
